--
-- PostgreSQL database dump
--


-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public."tblPurchaseOrder_TRAN" DROP CONSTRAINT IF EXISTS "tblPurchaseOrder_TRAN_item_id_15398968_fk_tblMaterial_id";
ALTER TABLE IF EXISTS ONLY public."tblPurchaseOrder_TRAN" DROP CONSTRAINT IF EXISTS "tblPurchaseOrder_TRAN_PONo_befb3715_fk_tblPurchaseOrder_po_no";
DROP INDEX IF EXISTS public."tblPurchaseOrder_supplier_id_0312ed54";
DROP INDEX IF EXISTS public."tblPurchaseOrder_po_no_8c945f8c_like";
DROP INDEX IF EXISTS public."tblPurchaseOrder_broker_id_afdaf2ce";
DROP INDEX IF EXISTS public."tblPurchaseOrder_TRAN_item_id_15398968";
DROP INDEX IF EXISTS public."tblPurchaseOrder_TRAN_PONo_befb3715_like";
DROP INDEX IF EXISTS public."tblPurchaseOrder_TRAN_PONo_befb3715";
DROP INDEX IF EXISTS public."tblPurchaseOrder_SalPurGroupID_10151954";
ALTER TABLE IF EXISTS ONLY public."tblPurchaseOrder" DROP CONSTRAINT IF EXISTS "tblPurchaseOrder_pkey";
ALTER TABLE IF EXISTS ONLY public."tblPurchaseOrder_TRAN" DROP CONSTRAINT IF EXISTS "tblPurchaseOrder_TRAN_pkey";
DROP TABLE IF EXISTS public."tblPurchaseOrder_TRAN";
DROP TABLE IF EXISTS public."tblPurchaseOrder";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tblPurchaseOrder; Type: TABLE; Schema: public; Owner: alpha_user
--

CREATE TABLE public."tblPurchaseOrder" (
    po_no character varying(50) NOT NULL,
    po_date timestamp with time zone NOT NULL,
    expected_delivery_date date,
    po_status character varying(20) NOT NULL,
    zone_name character varying(50) NOT NULL,
    supplier_contact character varying(50),
    supplier_address text,
    gst_number character varying(50),
    delivery_location character varying(100) NOT NULL,
    delivery_terms character varying(100) NOT NULL,
    payment_terms character varying(100) NOT NULL,
    freight_terms character varying(100) NOT NULL,
    currency character varying(10) NOT NULL,
    purchaser_name character varying(100),
    department character varying(50),
    cost_center character varying(50),
    special_instructions text,
    internal_notes text,
    total_basic_amount numeric(15,2) NOT NULL,
    taxes numeric(15,2) NOT NULL,
    grand_total numeric(15,2) NOT NULL,
    status boolean NOT NULL,
    user_created character varying(50),
    date_created timestamp with time zone NOT NULL,
    user_modified character varying(50),
    date_modified timestamp with time zone NOT NULL,
    broker_id integer,
    supplier_id integer NOT NULL,
    "SalPurGroupID" bigint
);


ALTER TABLE public."tblPurchaseOrder" OWNER TO alpha_user;

--
-- Name: tblPurchaseOrder_TRAN; Type: TABLE; Schema: public; Owner: alpha_user
--

CREATE TABLE public."tblPurchaseOrder_TRAN" (
    id bigint NOT NULL,
    order_qty numeric(15,4) NOT NULL,
    uom character varying(10) NOT NULL,
    unit_rate numeric(15,4) NOT NULL,
    amount numeric(15,2) NOT NULL,
    remarks character varying(200),
    user_created character varying(50),
    date_created timestamp with time zone,
    user_modified character varying(50),
    date_modified timestamp with time zone,
    item_id bigint NOT NULL,
    "PONo" character varying(50) NOT NULL
);


ALTER TABLE public."tblPurchaseOrder_TRAN" OWNER TO alpha_user;

--
-- Name: tblPurchaseOrder_TRAN_id_seq; Type: SEQUENCE; Schema: public; Owner: alpha_user
--

ALTER TABLE public."tblPurchaseOrder_TRAN" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."tblPurchaseOrder_TRAN_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: tblPurchaseOrder; Type: TABLE DATA; Schema: public; Owner: alpha_user
--

INSERT INTO public."tblPurchaseOrder" VALUES ('PO-202606-0002', '2026-06-18 05:30:00+05:30', '2026-06-24', 'Submitted', 'East Region', '9887884', 'Tokyo, Japan', '763', 'Plant 1', 'FOB-FOT-FOR', '30 Days Credit', 'Supplier Paid', 'EUR', 'Mahesh Patil', 'Production', 'Plant A', 'Everything is ohk', 'No need any changes', 83384.00, 15009.12, 98393.12, true, '', '2026-06-09 13:22:27.125168+05:30', NULL, '2026-06-09 13:22:27.125168+05:30', 9, 60, NULL);
INSERT INTO public."tblPurchaseOrder" VALUES ('PO-202606-0004', '2026-06-18 05:30:00+05:30', '2026-06-30', 'Submitted', 'South Region', '73663', 'nkhkf', '636', 'Plant 2', 'Ex Works/Ex-Godown', 'Advance', 'Supplier Paid', 'INR', 'lkrf', 'Purchase', 'Plant A', 'kfdng', 'knjfk', 68324.00, 0.00, 68324.00, true, '', '2026-06-18 17:03:29.83424+05:30', '', '2026-06-18 17:03:29.83424+05:30', NULL, 2, NULL);
INSERT INTO public."tblPurchaseOrder" VALUES ('PO-202606-0005', '2026-06-19 05:30:00+05:30', NULL, 'Submitted', 'South Region', '', '', '', 'Plant 2', 'Ex Works/Ex-Godown', 'Advance', 'Supplier Paid', 'INR', 'kjh', 'Purchase', 'Plant A', 'hkl', 'mnbj', 5829.00, 0.00, 5829.00, true, '', '2026-06-19 09:39:44.27886+05:30', '', '2026-06-19 09:39:44.27886+05:30', 4, 2, 15);
INSERT INTO public."tblPurchaseOrder" VALUES ('PO-202606-0003', '2026-06-18 05:30:00+05:30', '2026-06-23', 'Submitted', 'West Region', 'wdds', 'sads', '8665', 'Plant 2', 'Ex Works/Ex-Godown', 'Advance', 'Supplier Paid', 'INR', '', 'Purchase', 'Plant A', '', '', 764712.00, 137648.16, 902360.16, false, '', '2026-06-18 11:45:59.976834+05:30', '', '2026-06-19 09:39:54.014861+05:30', 2, 3, NULL);
INSERT INTO public."tblPurchaseOrder" VALUES ('PO-202606-0006', '2026-06-19 05:30:00+05:30', '2026-06-10', 'Submitted', 'West Region', '', '', '', 'Plant 2', 'Ex Works/Ex-Godown', 'Advance', 'Supplier Paid', 'INR', 'hghj', 'Purchase', 'Plant A', 'mb', 'nbj', 5655.00, 0.00, 5655.00, true, '', '2026-06-19 09:41:08.074742+05:30', '', '2026-06-19 09:41:08.074742+05:30', 0, 4, 15);
INSERT INTO public."tblPurchaseOrder" VALUES ('PO-202606-0007', '2026-06-19 05:30:00+05:30', NULL, 'Approved', 'West Region', '', '', '', 'Plant 1', 'Ex Works/Ex-Godown', 'Advance', 'Supplier Paid', 'INR', 'jhgj', 'Purchase', 'Plant A', 'ghjjk', 'hjgjfc', 4940.00, 0.00, 4940.00, false, '', '2026-06-19 09:44:39.379809+05:30', '', '2026-06-19 09:45:14.765341+05:30', 0, 2, 5);
INSERT INTO public."tblPurchaseOrder" VALUES ('PO-202606-0008', '2026-06-19 05:30:00+05:30', '2026-06-10', 'Submitted', 'West Region', '', '', '', 'Plant 2', 'Ex Works/Ex-Godown', 'Advance', 'Supplier Paid', 'INR', 'lkrfdd', 'Purchase', 'Plant A', 'sa', 'dfsa', 1024.00, 0.00, 1024.00, true, '', '2026-06-19 17:10:58.953884+05:30', '', '2026-06-19 17:10:58.953884+05:30', 0, 4, 15);


--
-- Data for Name: tblPurchaseOrder_TRAN; Type: TABLE DATA; Schema: public; Owner: alpha_user
--

INSERT INTO public."tblPurchaseOrder_TRAN" VALUES (3, 54.0000, 'KG', 766.0000, 41364.00, 'good services', '', '2026-06-09 13:22:27.125168+05:30', NULL, '2026-06-09 13:22:27.125168+05:30', 3, 'PO-202606-0002');
INSERT INTO public."tblPurchaseOrder_TRAN" VALUES (4, 55.0000, 'MT', 764.0000, 42020.00, 'good services', '', '2026-06-09 13:22:27.13286+05:30', NULL, '2026-06-09 13:22:27.13286+05:30', 6, 'PO-202606-0002');
INSERT INTO public."tblPurchaseOrder_TRAN" VALUES (22, 2223.0000, 'KG', 344.0000, 764712.00, '', '', '2026-06-18 11:46:13.951836+05:30', '', '2026-06-18 11:46:13.951836+05:30', 4, 'PO-202606-0003');
INSERT INTO public."tblPurchaseOrder_TRAN" VALUES (23, 76.0000, 'MT', 899.0000, 68324.00, 'kjrh', '', '2026-06-18 17:03:29.83424+05:30', '', '2026-06-18 17:03:29.83424+05:30', 10, 'PO-202606-0004');
INSERT INTO public."tblPurchaseOrder_TRAN" VALUES (24, 87.0000, 'MT', 67.0000, 5829.00, '', '', '2026-06-19 09:39:44.27886+05:30', '', '2026-06-19 09:39:44.27886+05:30', 8, 'PO-202606-0005');
INSERT INTO public."tblPurchaseOrder_TRAN" VALUES (25, 65.0000, 'MT', 87.0000, 5655.00, '', '', '2026-06-19 09:41:08.074742+05:30', '', '2026-06-19 09:41:08.074742+05:30', 5, 'PO-202606-0006');
INSERT INTO public."tblPurchaseOrder_TRAN" VALUES (26, 65.0000, 'MT', 76.0000, 4940.00, '', '', '2026-06-19 09:44:39.379809+05:30', '', '2026-06-19 09:44:39.379809+05:30', 2, 'PO-202606-0007');
INSERT INTO public."tblPurchaseOrder_TRAN" VALUES (27, 32.0000, 'MT', 32.0000, 1024.00, '', '', '2026-06-19 17:10:58.953884+05:30', '', '2026-06-19 17:10:58.953884+05:30', 5, 'PO-202606-0008');


--
-- Name: tblPurchaseOrder_TRAN_id_seq; Type: SEQUENCE SET; Schema: public; Owner: alpha_user
--

SELECT pg_catalog.setval('public."tblPurchaseOrder_TRAN_id_seq"', 27, true);


--
-- Name: tblPurchaseOrder_TRAN tblPurchaseOrder_TRAN_pkey; Type: CONSTRAINT; Schema: public; Owner: alpha_user
--

ALTER TABLE ONLY public."tblPurchaseOrder_TRAN"
    ADD CONSTRAINT "tblPurchaseOrder_TRAN_pkey" PRIMARY KEY (id);


--
-- Name: tblPurchaseOrder tblPurchaseOrder_pkey; Type: CONSTRAINT; Schema: public; Owner: alpha_user
--

ALTER TABLE ONLY public."tblPurchaseOrder"
    ADD CONSTRAINT "tblPurchaseOrder_pkey" PRIMARY KEY (po_no);


--
-- Name: tblPurchaseOrder_SalPurGroupID_10151954; Type: INDEX; Schema: public; Owner: alpha_user
--

CREATE INDEX "tblPurchaseOrder_SalPurGroupID_10151954" ON public."tblPurchaseOrder" USING btree ("SalPurGroupID");


--
-- Name: tblPurchaseOrder_TRAN_PONo_befb3715; Type: INDEX; Schema: public; Owner: alpha_user
--

CREATE INDEX "tblPurchaseOrder_TRAN_PONo_befb3715" ON public."tblPurchaseOrder_TRAN" USING btree ("PONo");


--
-- Name: tblPurchaseOrder_TRAN_PONo_befb3715_like; Type: INDEX; Schema: public; Owner: alpha_user
--

CREATE INDEX "tblPurchaseOrder_TRAN_PONo_befb3715_like" ON public."tblPurchaseOrder_TRAN" USING btree ("PONo" varchar_pattern_ops);


--
-- Name: tblPurchaseOrder_TRAN_item_id_15398968; Type: INDEX; Schema: public; Owner: alpha_user
--

CREATE INDEX "tblPurchaseOrder_TRAN_item_id_15398968" ON public."tblPurchaseOrder_TRAN" USING btree (item_id);


--
-- Name: tblPurchaseOrder_broker_id_afdaf2ce; Type: INDEX; Schema: public; Owner: alpha_user
--

CREATE INDEX "tblPurchaseOrder_broker_id_afdaf2ce" ON public."tblPurchaseOrder" USING btree (broker_id);


--
-- Name: tblPurchaseOrder_po_no_8c945f8c_like; Type: INDEX; Schema: public; Owner: alpha_user
--

CREATE INDEX "tblPurchaseOrder_po_no_8c945f8c_like" ON public."tblPurchaseOrder" USING btree (po_no varchar_pattern_ops);


--
-- Name: tblPurchaseOrder_supplier_id_0312ed54; Type: INDEX; Schema: public; Owner: alpha_user
--

CREATE INDEX "tblPurchaseOrder_supplier_id_0312ed54" ON public."tblPurchaseOrder" USING btree (supplier_id);


--
-- Name: tblPurchaseOrder_TRAN tblPurchaseOrder_TRAN_PONo_befb3715_fk_tblPurchaseOrder_po_no; Type: FK CONSTRAINT; Schema: public; Owner: alpha_user
--

ALTER TABLE ONLY public."tblPurchaseOrder_TRAN"
    ADD CONSTRAINT "tblPurchaseOrder_TRAN_PONo_befb3715_fk_tblPurchaseOrder_po_no" FOREIGN KEY ("PONo") REFERENCES public."tblPurchaseOrder"(po_no) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tblPurchaseOrder_TRAN tblPurchaseOrder_TRAN_item_id_15398968_fk_tblMaterial_id; Type: FK CONSTRAINT; Schema: public; Owner: alpha_user
--

ALTER TABLE ONLY public."tblPurchaseOrder_TRAN"
    ADD CONSTRAINT "tblPurchaseOrder_TRAN_item_id_15398968_fk_tblMaterial_id" FOREIGN KEY (item_id) REFERENCES public."tblMaterial"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


