# Generated by Django 6.0.3 on 2026-03-28 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50, verbose_name='Category Name')),
                ('categoryType', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Category Type')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'tblCategory',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True, verbose_name='Voucher Number')),
                ('voucher_date', models.DateField(verbose_name='Voucher Date')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active (soft delete).', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-voucher_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alpha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier code.', max_length=50, unique=True, verbose_name='Alpha Code')),
                ('alpha_name', models.CharField(max_length=100, verbose_name='Alpha Name')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(db_column='categoryID', on_delete=django.db.models.deletion.PROTECT, to='dashboard.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Alpha Record',
                'verbose_name_plural': 'Alpha Records',
                'db_table': 'tblAlphagroup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(choices=[('A', 'Type A'), ('B', 'Type B')], max_length=1, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('alpha_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.alpha', verbose_name='Alpha Group')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='dashboard.voucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'Voucher Fact',
                'verbose_name_plural': 'Voucher Facts',
            },
        ),
    ]
