# Generated by Django 6.0.3 on 2026-03-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpha',
            name='alpha_name',
            field=models.CharField(db_column='Alpha Group Name', max_length=50, verbose_name='Alpha Name'),
        ),
    ]
