# Generated by Django 6.0.3 on 2026-03-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_alpha_alpha_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Voucher Number'),
        ),
    ]
