# Generated by Django 4.2 on 2026-04-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_voucher_voucher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherfact',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='voucherfact',
            name='voucher_date',
            field=models.DateField(blank=True, null=True, verbose_name='Voucher Date'),
        ),
        migrations.AlterField(
            model_name='alpha',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucherfact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
