# Generated by Django 4.2 on 2026-05-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_voucherfact_remarks_voucherfact_voucher_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBank',
            fields=[
                ('voucher_no', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Voucher No')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('tran_type', models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK')], max_length=4, verbose_name='TranType')),
                ('rpid', models.CharField(choices=[('R', 'Receipt'), ('P', 'Payment'), ('I', 'Issue'), ('D', 'Deposit')], max_length=1, verbose_name='RPID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Amount')),
                ('narration', models.CharField(blank=True, max_length=200, null=True, verbose_name='Narration')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('user_created', models.CharField(blank=True, max_length=50, null=True, verbose_name='UserCreated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='DateCreated')),
                ('user_modified', models.CharField(blank=True, max_length=50, null=True, verbose_name='UserModified')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='DateModified')),
            ],
            options={
                'verbose_name': 'Cash/Bank Transaction',
                'verbose_name_plural': 'Cash/Bank Transactions',
                'db_table': 'tblCASHBANK',
                'ordering': ['-date', '-date_created'],
            },
        ),
        migrations.AlterField(
            model_name='voucherfact',
            name='row_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='CashBankTran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('tran_type', models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK')], max_length=4, verbose_name='TranType')),
                ('rpid', models.CharField(choices=[('R', 'Receipt'), ('P', 'Payment'), ('I', 'Issue'), ('D', 'Deposit')], max_length=1, verbose_name='RPID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks')),
                ('chq_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='ChqNo')),
                ('chq_date', models.DateField(blank=True, null=True, verbose_name='ChqDate')),
                ('payee_bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='PayeeBank')),
                ('user_created', models.CharField(blank=True, max_length=50, null=True, verbose_name='UserCreated')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DateCreated')),
                ('user_modified', models.CharField(blank=True, max_length=50, null=True, verbose_name='UserModified')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='DateModified')),
                ('voucher', models.ForeignKey(db_column='VoucherNo', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dashboard.cashbank', verbose_name='VoucherNo')),
            ],
            options={
                'verbose_name': 'Cash/Bank Detail',
                'verbose_name_plural': 'Cash/Bank Details',
                'db_table': 'tblCASHBANK_TRAN',
            },
        ),
    ]
