# Generated by Django 4.2 on 2026-05-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_cashbank_alter_voucherfact_row_type_cashbanktran'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbanktran',
            name='alpha_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.alpha', verbose_name='Account/Alpha Group'),
        ),
    ]
