# Generated by Django 6.0.3 on 2026-05-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_sectionc_alter_alpha_id_alter_cashbanktran_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbank',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_column='BankAccount', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbank_transactions', to='dashboard.alpha', verbose_name='Bank Account'),
        ),
    ]
