# Generated by Django 6.0.3 on 2026-05-19 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_bank_account_to_cashbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionc',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_column='BankAccount', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sectionc_transactions', to='dashboard.alpha', verbose_name='Bank Account'),
        ),
    ]
