# Generated by Django 6.0.3 on 2026-05-22 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_bank_account_to_sectionc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsectionB2',
            fields=[
                ('voucher_no', models.CharField(help_text='Auto-generated: B2-YYYYMM-NNNN. Read-only after creation.', max_length=50, primary_key=True, serialize=False, verbose_name='Voucher No')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('tran_type', models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK')], max_length=4, verbose_name='Tran Type')),
                ('rpid', models.CharField(choices=[('R', 'Receipt'), ('P', 'Payment'), ('I', 'Issue'), ('D', 'Deposit')], max_length=1, verbose_name='RPID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Must equal the sum of all detail row amounts.', max_digits=15, verbose_name='Amount')),
                ('narration', models.CharField(blank=True, max_length=200, null=True, verbose_name='Narration')),
                ('ref_voucher_no', models.CharField(blank=True, help_text='Optional reference to a Sub Section B (CashBank) voucher.', max_length=50, null=True, verbose_name='Ref Voucher No')),
                ('status', models.BooleanField(default=True, help_text='False = soft-deleted. Never hard-deleted via UI.', verbose_name='Status')),
                ('user_created', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Created')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('user_modified', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Modified')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('bank_account', models.ForeignKey(blank=True, db_column='BankAccount', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b2_transactions', to='dashboard.alpha', verbose_name='Bank Account')),
            ],
            options={
                'verbose_name': 'Sub Section B-2 Transaction',
                'verbose_name_plural': 'Sub Section B-2 Transactions',
                'db_table': 'tblSubsectionB2',
                'ordering': ['-date', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SubsectionB2Tran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Inherited from header if not provided.', verbose_name='Date')),
                ('tran_type', models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK')], help_text='Inherited from header if not provided.', max_length=4, verbose_name='Tran Type')),
                ('rpid', models.CharField(choices=[('R', 'Receipt'), ('P', 'Payment'), ('I', 'Issue'), ('D', 'Deposit')], help_text='Inherited from header if not provided.', max_length=1, verbose_name='RPID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks')),
                ('cost_center', models.CharField(blank=True, help_text='Optional cost center code for dashboard aggregation.', max_length=50, null=True, verbose_name='Cost Center')),
                ('user_created', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Created')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('user_modified', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Modified')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('alpha_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.alpha', verbose_name='Account / Alpha Group')),
                ('voucher', models.ForeignKey(db_column='VoucherNo', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dashboard.subsectionb2', verbose_name='Voucher No')),
            ],
            options={
                'verbose_name': 'Sub Section B-2 Detail',
                'verbose_name_plural': 'Sub Section B-2 Details',
                'db_table': 'tblSubsectionB2_TRAN',
            },
        ),
    ]
