# Generated by Django 6.0.3 on 2026-05-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_add_subsection_b2'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsectionb2tran',
            name='chq_date',
            field=models.DateField(blank=True, null=True, verbose_name='ChqDate'),
        ),
        migrations.AddField(
            model_name='subsectionb2tran',
            name='chq_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ChqNo'),
        ),
        migrations.AddField(
            model_name='subsectionb2tran',
            name='payee_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PayeeBank'),
        ),
    ]
