# Generated by Django 6.0.3 on 2026-05-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_subsection_b2_triggers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsectionb2',
            options={'ordering': ['-transaction_date', '-date_created'], 'verbose_name': 'Sub Section B-2 Transaction', 'verbose_name_plural': 'Sub Section B-2 Transactions'},
        ),
        migrations.AlterField(
            model_name='subsectionb2',
            name='transaction_date',
            field=models.DateTimeField(db_column='transaction_date', help_text='Voucher date and time.', verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='subsectionb2tran',
            name='transaction_date',
            field=models.DateTimeField(db_column='transaction_date', help_text='Inherited from header if not provided.', verbose_name='Transaction Date'),
        ),
    ]
