# Generated by Django 6.0.3 on 2026-05-28 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_cashbank_b2_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=20, unique=True, verbose_name='Material Code')),
                ('material_name', models.CharField(max_length=50, verbose_name='Material Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': 'tblMaterial',
                'ordering': ['material_name'],
            },
        ),
        migrations.CreateModel(
            name='GateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_pass_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Gate Pass ID')),
                ('entry_datetime', models.DateTimeField(verbose_name='Entry Time')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Vehicle Number')),
                ('driver_name', models.CharField(max_length=50, verbose_name='Driver Name')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='Driver Photo (Base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_entries', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_entries', to='dashboard.alpha', verbose_name='Supplier')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_entries', to='dashboard.material', verbose_name='Material Type')),
            ],
            options={
                'verbose_name': 'Gate Entry',
                'verbose_name_plural': 'Gate Entries',
                'db_table': 'tblGateEntry',
                'ordering': ['-created_at'],
            },
        ),
    ]
