# Generated by Django 6.0.3 on 2026-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_material_gateentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpha',
            name='cl_bal',
            field=models.DecimalField(db_column='CL_BAL', decimal_places=2, default=0.0, max_digits=15, verbose_name='Closing Balance'),
        ),
    ]
