# Generated by Django 6.0.3 on 2026-06-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_sp_manage_transaction'),
    ]

    operations = [
        # 0. Drop PostgreSQL varchar_pattern_ops index on code column if exists
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS "tblAlphagroup_code_a7dc41d1_like";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 1. Update code to unique numeric string to satisfy constraints and allow bigint casting
        migrations.RunSQL(
            sql='UPDATE "tblAlphagroup" SET "code" = CAST("id" as varchar);',
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 2. Rename alpha_name to Account_Name
        migrations.RenameField(
            model_name='alpha',
            old_name='alpha_name',
            new_name='Account_Name',
        ),
        # 3. Alter Account_Name field to match model definition (updating db_column to 'Account_Name')
        migrations.AlterField(
            model_name='alpha',
            name='Account_Name',
            field=models.CharField(db_column='Account_Name', max_length=50, verbose_name='Account Name'),
        ),
        # 4. Rename code to groupID
        migrations.RenameField(
            model_name='alpha',
            old_name='code',
            new_name='groupID',
        ),
        # 5. Alter groupID to BigIntegerField
        migrations.AlterField(
            model_name='alpha',
            name='groupID',
            field=models.BigIntegerField(blank=True, db_column='groupID', null=True, verbose_name='Group ID'),
        ),
    ]
