# Generated by Django 6.0.3 on 2026-06-09 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_unify_cashbank_sp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'managed': True, 'ordering': ['-voucher_date', '-created_at'], 'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='voucherfact',
            options={'managed': True, 'verbose_name': 'Voucher Fact', 'verbose_name_plural': 'Voucher Facts'},
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_no', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='PO No')),
                ('po_date', models.DateTimeField(verbose_name='PO Date')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date')),
                ('po_status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Released', 'Released')], default='Draft', max_length=20, verbose_name='PO Status')),
                ('zone_name', models.CharField(max_length=50, verbose_name='Zone Name')),
                ('supplier_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier Contact')),
                ('supplier_address', models.TextField(blank=True, null=True, verbose_name='Supplier Address')),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='GST Number')),
                ('delivery_location', models.CharField(max_length=100, verbose_name='Delivery Location')),
                ('delivery_terms', models.CharField(max_length=100, verbose_name='Delivery Terms/Incoterms')),
                ('payment_terms', models.CharField(max_length=100, verbose_name='Payment Terms')),
                ('freight_terms', models.CharField(max_length=100, verbose_name='Freight Terms')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('purchaser_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchaser Name')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department')),
                ('cost_center', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cost Center')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Special Instructions')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('total_basic_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Basic Amount')),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Taxes')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Grand Total')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('user_created', models.CharField(blank=True, max_length=50, null=True, verbose_name='UserCreated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='DateCreated')),
                ('user_modified', models.CharField(blank=True, max_length=50, null=True, verbose_name='UserModified')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='DateModified')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='broker_pos', to='dashboard.alpha', verbose_name='Broker Name')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_pos', to='dashboard.alpha', verbose_name='Supplier Name')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'tblPurchaseOrder',
                'ordering': ['-po_date', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qty', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Order Qty')),
                ('uom', models.CharField(max_length=10, verbose_name='UOM')),
                ('unit_rate', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Unit Rate')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks')),
                ('user_created', models.CharField(blank=True, max_length=50, null=True, verbose_name='UserCreated')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DateCreated')),
                ('user_modified', models.CharField(blank=True, max_length=50, null=True, verbose_name='UserModified')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='DateModified')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.material', verbose_name='Item Code & Name')),
                ('purchase_order', models.ForeignKey(db_column='PONo', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.purchaseorder', verbose_name='PONo')),
            ],
            options={
                'verbose_name': 'Purchase Order Detail',
                'verbose_name_plural': 'Purchase Order Details',
                'db_table': 'tblPurchaseOrder_TRAN',
            },
        ),
    ]
