# Generated by Django 6.0.3 on 2026-06-10 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_purchase_order_sp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('BrokerID', models.IntegerField(db_column='BrokerID', primary_key=True, serialize=False)),
                ('BrokerName', models.CharField(db_column='BrokerName', max_length=100)),
                ('BrokerAddress', models.CharField(blank=True, db_column='BrokerAddress', max_length=255, null=True)),
                ('ContactNo', models.CharField(blank=True, db_column='ContactNo', max_length=50, null=True)),
                ('PANo', models.CharField(blank=True, db_column='PANo', max_length=50, null=True)),
                ('UserCreated', models.CharField(blank=True, db_column='UserCreated', max_length=50, null=True)),
                ('DateCreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('UserModified', models.CharField(blank=True, db_column='UserModified', max_length=50, null=True)),
                ('DateModified', models.DateTimeField(blank=True, db_column='DateModified', null=True)),
            ],
            options={
                'db_table': 'tblBroker',
                'ordering': ['BrokerName'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorSupplier',
            fields=[
                ('VendorSupplierID', models.IntegerField(db_column='VendorSupplierID', primary_key=True, serialize=False)),
                ('VendorSupplierName', models.CharField(db_column='VendorSupplierName', max_length=100)),
                ('Address1', models.CharField(blank=True, db_column='Address1', max_length=255, null=True)),
                ('Address2', models.CharField(blank=True, db_column='Address2', max_length=255, null=True)),
                ('ContactNo', models.CharField(blank=True, db_column='ContactNo', max_length=50, null=True)),
                ('GSTNo', models.CharField(blank=True, db_column='GSTNo', max_length=50, null=True)),
                ('PANo', models.CharField(blank=True, db_column='PANo', max_length=50, null=True)),
                ('UserCreted', models.CharField(blank=True, db_column='UserCreted', max_length=50, null=True)),
                ('DateCreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('UserModified', models.CharField(blank=True, db_column='UserModified', max_length=50, null=True)),
                ('DateModified', models.DateTimeField(blank=True, db_column='DateModified', null=True)),
            ],
            options={
                'db_table': 'tblVendorSupplier',
                'ordering': ['VendorSupplierName'],
                'managed': True,
            },
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "tblPurchaseOrder" DROP CONSTRAINT IF EXISTS "tblPurchaseOrder_broker_id_afdaf2ce_fk_tblAlphagroup_id", DROP CONSTRAINT IF EXISTS "tblPurchaseOrder_supplier_id_0312ed54_fk_tblAlphagroup_id";',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='broker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='broker_pos', to='dashboard.broker', verbose_name='Broker Name'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_pos', to='dashboard.vendorsupplier', verbose_name='Supplier Name'),
        ),
    ]
