# Generated by Django 6.0.3 on 2026-06-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_fix_delete_cascades'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalPurGroup',
            fields=[
                ('SalPurGroupID', models.BigAutoField(db_column='SalPurGroupID', primary_key=True, serialize=False)),
                ('SalPurGroupName', models.CharField(blank=True, db_column='SalPurGroupName', max_length=255, null=True)),
                ('GroupwiseAccounting', models.BooleanField(blank=True, db_column='GroupwiseAccounting', null=True)),
                ('UserCreated', models.CharField(blank=True, db_column='UserCreated', max_length=100, null=True)),
                ('DateCreated', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('UserModified', models.CharField(blank=True, db_column='UserModified', max_length=100, null=True)),
                ('DateModified', models.DateTimeField(auto_now=True, db_column='DateModified', null=True)),
            ],
            options={
                'verbose_name': 'Sales/Purchase Group',
                'verbose_name_plural': 'Sales/Purchase Groups',
                'db_table': 'tblSalPurGroup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalPurGroupTran',
            fields=[
                ('ID', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ChargesName', models.CharField(blank=True, db_column='ChargesName', max_length=255, null=True)),
                ('Auto_Y_Manual_N', models.BooleanField(blank=True, db_column='Auto_Y_Manual_N', null=True)),
                ('Rate', models.DecimalField(blank=True, db_column='Rate', decimal_places=4, max_digits=18, null=True)),
                ('Debit_D_Credit_C', models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], db_column='Debit_D_Credit_C', max_length=1, null=True)),
                ('UserCreated', models.CharField(blank=True, db_column='UserCreated', max_length=100, null=True)),
                ('DateCreated', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('UserModified', models.CharField(blank=True, db_column='UserModified', max_length=100, null=True)),
                ('DateModified', models.DateTimeField(auto_now=True, db_column='DateModified', null=True)),
            ],
            options={
                'verbose_name': 'Sales/Purchase Group Transaction',
                'verbose_name_plural': 'Sales/Purchase Group Transactions',
                'db_table': 'tblSalPurGroup_Tran',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='accountmaster',
            options={'ordering': ['-created_at'], 'verbose_name': 'Account Master Record', 'verbose_name_plural': 'Account Master Records'},
        ),
        migrations.AddField(
            model_name='cashbank',
            name='Interstate_Y_WithinState_N',
            field=models.BooleanField(blank=True, null=True, verbose_name='Interstate (Yes) / Within State (No)'),
        ),
    ]
