# Generated by Django 6.0.3 on 2026-06-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_salpurgroup_salpurgrouptran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbank',
            name='GST_Applicable_Y_N',
            field=models.BooleanField(blank=True, null=True, verbose_name='GST Applicable Y/N'),
        ),
    ]
