# Generated by Django 6.0.3 on 2026-06-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_cashbank_gst_applicable_y_n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salpurgroup',
            options={'managed': True, 'verbose_name': 'Sales/Purchase Group', 'verbose_name_plural': 'Sales/Purchase Groups'},
        ),
        migrations.AlterModelOptions(
            name='salpurgrouptran',
            options={'managed': True, 'verbose_name': 'Sales/Purchase Group Transaction', 'verbose_name_plural': 'Sales/Purchase Group Transactions'},
        ),
    ]
