# Generated by Django 6.0.3 on 2026-06-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_salpurgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salpurgroup',
            options={'managed': True, 'verbose_name': 'Sales/Purchase Group', 'verbose_name_plural': 'Sales/Purchase Groups'},
        ),
        migrations.AlterModelOptions(
            name='salpurgrouptran',
            options={'managed': True, 'verbose_name': 'Sales/Purchase Group Transaction', 'verbose_name_plural': 'Sales/Purchase Group Transactions'},
        ),
        migrations.RemoveField(
            model_name='cashbank',
            name='GST_Applicable_Y_N',
        ),
        migrations.RemoveField(
            model_name='cashbank',
            name='Interstate_Y_WithinState_N',
        ),
    ]
