# Generated by Django 6.0.3 on 2026-06-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_salpurgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurSales',
            fields=[
                ('VoucherNo', models.CharField(db_column='VoucherNo', max_length=100)),
                ('VoucherDate', models.DateField(db_column='VoucherDate')),
                ('TranType', models.CharField(db_column='TranType', max_length=20)),
                ('OrderNo', models.CharField(db_column='OrderNo', max_length=100, primary_key=True, serialize=False)),
                ('OrderDate', models.DateField(db_column='OrderDate')),
                ('ZoneID', models.BigIntegerField(blank=True, db_column='ZoneID', null=True)),
                ('DeliveryLocation', models.CharField(blank=True, db_column='DeliveryLocation', max_length=255, null=True)),
                ('DelTermsID', models.BigIntegerField(blank=True, db_column='DelTermsID', null=True)),
                ('PaymentTermsID', models.BigIntegerField(blank=True, db_column='PaymentTermsID', null=True)),
                ('FreightTermID', models.BigIntegerField(blank=True, db_column='FreightTermID', null=True)),
                ('CurrencyID', models.BigIntegerField(blank=True, db_column='CurrencyID', null=True)),
                ('IncotermID', models.BigIntegerField(blank=True, db_column='IncotermID', null=True)),
                ('Purchaser_Saleman_ID', models.BigIntegerField(blank=True, db_column='Purchaser_Saleman_ID', null=True)),
                ('DepartmentID', models.BigIntegerField(blank=True, db_column='DepartmentID', null=True)),
                ('CostCentrID', models.BigIntegerField(blank=True, db_column='CostCentrID', null=True)),
                ('SpecialInstructions', models.CharField(blank=True, db_column='SpecialInstructions', max_length=255, null=True)),
                ('InternalNotes', models.CharField(blank=True, db_column='InternalNotes', max_length=1, null=True)),
                ('UserCreated', models.CharField(blank=True, db_column='UserCreated', max_length=100, null=True)),
                ('DatdCreated', models.DateField(blank=True, db_column='DatdCreated', null=True)),
                ('UserModified', models.CharField(blank=True, db_column='UserModified', max_length=100, null=True)),
                ('DateModified', models.DateField(blank=True, db_column='DateModified', null=True)),
                ('IGST0_SGST1', models.SmallIntegerField(blank=True, db_column='IGST0_SGST1', null=True)),
            ],
            options={
                'verbose_name': 'Purchase/Sales Header',
                'verbose_name_plural': 'Purchase/Sales Headers',
                'db_table': 'tblPurSales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PurSalesTran',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('VoucherNo', models.CharField(db_column='VoucherNo', max_length=100)),
                ('VoucherDate', models.DateField(db_column='VoucherDate')),
                ('TranType', models.CharField(db_column='TranType', max_length=20)),
                ('Bag', models.BigIntegerField(blank=True, db_column='Bag', null=True)),
                ('Weight', models.DecimalField(blank=True, db_column='Weight', decimal_places=3, max_digits=18, null=True)),
                ('unit_weight', models.DecimalField(blank=True, db_column='unit_weight', decimal_places=3, max_digits=18, null=True)),
                ('Unit_rate', models.DecimalField(blank=True, db_column='Unit_rate', decimal_places=2, max_digits=18, null=True)),
                ('Amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=18, null=True)),
                ('gst_rate', models.DecimalField(blank=True, db_column='gst_rate', decimal_places=2, max_digits=18, null=True)),
                ('IGST', models.DecimalField(blank=True, db_column='IGST', decimal_places=2, max_digits=18, null=True)),
                ('CGST', models.DecimalField(blank=True, db_column='CGST', decimal_places=2, max_digits=18, null=True)),
                ('SGST', models.DecimalField(blank=True, db_column='SGST', decimal_places=2, max_digits=18, null=True)),
                ('Total', models.DecimalField(blank=True, db_column='Total', decimal_places=2, max_digits=18, null=True)),
                ('IsRateIncludingGST', models.BooleanField(blank=True, db_column='IsRateIncludingGST', null=True)),
                ('UserCreated', models.CharField(blank=True, db_column='UserCreated', max_length=100, null=True)),
                ('DateCreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('UserModified', models.CharField(blank=True, db_column='UserModified', max_length=100, null=True)),
                ('DateModified', models.DateTimeField(blank=True, db_column='DateModified', null=True)),
            ],
            options={
                'verbose_name': 'Purchase/Sales Detail',
                'verbose_name_plural': 'Purchase/Sales Details',
                'db_table': 'tblPurSales_Tran',
                'managed': True,
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE "tblMaterial" ADD COLUMN IF NOT EXISTS "Auto1_Manual0_calc" boolean;
                    ALTER TABLE "tblMaterial" ADD COLUMN IF NOT EXISTS "IsRateInclGSTY1N0" boolean;
                    ALTER TABLE "tblMaterial" ADD COLUMN IF NOT EXISTS "PurchaseGST" numeric(5,2);
                    ALTER TABLE "tblMaterial" ADD COLUMN IF NOT EXISTS "SalesGST" numeric(6,2);
                    ALTER TABLE "tblMaterial" ADD COLUMN IF NOT EXISTS "unit_weight" numeric(18,3);
                    """,
                    reverse_sql="""
                    ALTER TABLE "tblMaterial" DROP COLUMN IF EXISTS "Auto1_Manual0_calc";
                    ALTER TABLE "tblMaterial" DROP COLUMN IF EXISTS "IsRateInclGSTY1N0";
                    ALTER TABLE "tblMaterial" DROP COLUMN IF EXISTS "PurchaseGST";
                    ALTER TABLE "tblMaterial" DROP COLUMN IF EXISTS "SalesGST";
                    ALTER TABLE "tblMaterial" DROP COLUMN IF EXISTS "unit_weight";
                    """
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='material',
                    name='Auto1_Manual0_calc',
                    field=models.BooleanField(blank=True, db_column='Auto1_Manual0_calc', null=True, verbose_name='Auto1 Manual0 Calc'),
                ),
                migrations.AddField(
                    model_name='material',
                    name='IsRateInclGSTY1N0',
                    field=models.BooleanField(blank=True, db_column='IsRateInclGSTY1N0', null=True, verbose_name='Is Rate Incl GST Y1N0'),
                ),
                migrations.AddField(
                    model_name='material',
                    name='PurchaseGST',
                    field=models.DecimalField(blank=True, db_column='PurchaseGST', decimal_places=2, max_digits=5, null=True, verbose_name='Purchase GST'),
                ),
                migrations.AddField(
                    model_name='material',
                    name='SalesGST',
                    field=models.DecimalField(blank=True, db_column='SalesGST', decimal_places=2, max_digits=6, null=True, verbose_name='Sales GST'),
                ),
                migrations.AddField(
                    model_name='material',
                    name='unit_weight',
                    field=models.DecimalField(blank=True, db_column='unit_weight', decimal_places=3, max_digits=18, null=True, verbose_name='Unit Weight'),
                ),
            ]
        ),
    ]
