# Generated by Django 6.0.3 on 2026-06-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_pursales_pursalestran_material_auto1_manual0_calc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('ZoneID', models.BigAutoField(db_column='ZoneID', primary_key=True, serialize=False)),
                ('ZoneName', models.CharField(db_column='ZoneName', max_length=255)),
            ],
            options={
                'db_table': 'tblZone',
                'ordering': ['ZoneName'],
                'managed': True,
            },
        ),
    ]
