# Generated by Django 6.0.3 on 2026-06-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'managed': False, 'ordering': ['BrokerName']},
        ),
        migrations.AlterModelOptions(
            name='pursales',
            options={'managed': False, 'verbose_name': 'Purchase/Sales Header', 'verbose_name_plural': 'Purchase/Sales Headers'},
        ),
        migrations.AlterModelOptions(
            name='pursalestran',
            options={'managed': False, 'verbose_name': 'Purchase/Sales Detail', 'verbose_name_plural': 'Purchase/Sales Details'},
        ),
        migrations.AlterModelOptions(
            name='salpurgroup',
            options={'managed': False, 'verbose_name': 'Sales/Purchase Group', 'verbose_name_plural': 'Sales/Purchase Groups'},
        ),
        migrations.AlterModelOptions(
            name='salpurgrouptran',
            options={'managed': False, 'verbose_name': 'Sales/Purchase Group Transaction', 'verbose_name_plural': 'Sales/Purchase Group Transactions'},
        ),
        migrations.AlterModelOptions(
            name='vendorsupplier',
            options={'managed': False, 'ordering': ['VendorSupplierName']},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'managed': False, 'ordering': ['-voucher_date', '-created_at'], 'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='voucherfact',
            options={'managed': False, 'verbose_name': 'Voucher Fact', 'verbose_name_plural': 'Voucher Facts'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'managed': False, 'ordering': ['ZoneName']},
        ),
        migrations.AlterField(
            model_name='accountmaster',
            name='cl_bal',
            field=models.DecimalField(db_column='CL_BAL', decimal_places=2, default=0.0, max_digits=15, verbose_name='Opening Balance'),
        ),
    ]
