# Generated by Django 6.0.3 on 2026-06-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_broker_options_alter_pursales_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pursales',
            options={'managed': True, 'verbose_name': 'Purchase/Sales Header', 'verbose_name_plural': 'Purchase/Sales Headers'},
        ),
        migrations.AlterModelOptions(
            name='pursalestran',
            options={'managed': True, 'verbose_name': 'Purchase/Sales Detail', 'verbose_name_plural': 'Purchase/Sales Details'},
        ),
        migrations.AlterModelOptions(
            name='salpurgroup',
            options={'managed': True, 'verbose_name': 'Sales/Purchase Group', 'verbose_name_plural': 'Sales/Purchase Groups'},
        ),
        migrations.AlterModelOptions(
            name='salpurgrouptran',
            options={'managed': True, 'verbose_name': 'Sales/Purchase Group Transaction', 'verbose_name_plural': 'Sales/Purchase Group Transactions'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'managed': True, 'ordering': ['-voucher_date', '-created_at'], 'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='voucherfact',
            options={'managed': True, 'verbose_name': 'Voucher Fact', 'verbose_name_plural': 'Voucher Facts'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'managed': True, 'ordering': ['ZoneName']},
        ),
    ]
