# Generated by Django 6.0.3 on 2026-06-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class AddFieldIfNotExists(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)
        table_name = model._meta.db_table
        column_name = field.column

        if schema_editor.connection.vendor == 'sqlite':
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(f"PRAGMA table_info({table_name})")
                columns = [row[1] for row in cursor.fetchall()]
                exists = column_name in columns
        else:
            with schema_editor.connection.cursor() as cursor:
                # PostgreSQL case-sensitive column check
                cursor.execute(
                    "SELECT 1 FROM information_schema.columns WHERE table_name = %s AND column_name = %s",
                    [table_name, column_name]
                )
                exists = bool(cursor.fetchone())

        if not exists:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_alter_pursales_options_alter_pursalestran_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'managed': False, 'ordering': ['-voucher_date', '-created_at'], 'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='voucherfact',
            options={'managed': False, 'verbose_name': 'Voucher Fact', 'verbose_name_plural': 'Voucher Facts'},
        ),
        AddFieldIfNotExists(
            model_name='purchaseorder',
            name='sal_pur_group',
            field=models.ForeignKey(blank=True, db_column='SalPurGroupID', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='dashboard.salpurgroup', verbose_name='Sales/Purchase Group'),
        ),
        AddFieldIfNotExists(
            model_name='pursales',
            name='BrokerID',
            field=models.ForeignKey(blank=True, db_column='BrokerID', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.broker'),
        ),
        AddFieldIfNotExists(
            model_name='pursales',
            name='CreditDays',
            field=models.IntegerField(blank=True, db_column='CreditDays', default=0, null=True),
        ),
        AddFieldIfNotExists(
            model_name='pursales',
            name='PartyID',
            field=models.ForeignKey(blank=True, db_column='PartyID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pursales_party_records', to='dashboard.accountmaster'),
        ),
        AddFieldIfNotExists(
            model_name='pursales',
            name='PurSalGroupID',
            field=models.ForeignKey(blank=True, db_column='PurSalGroupID', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.salpurgroup'),
        ),
        AddFieldIfNotExists(
            model_name='pursalestran',
            name='Item_ID',
            field=models.ForeignKey(blank=True, db_column='Item_ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.material'),
        ),
        AddFieldIfNotExists(
            model_name='salpurgroup',
            name='GST_Applicable_Y_N',
            field=models.BooleanField(blank=True, db_column='GST_Applicable_Y_N', null=True, verbose_name='GST Applicable Y/N'),
        ),
        AddFieldIfNotExists(
            model_name='salpurgroup',
            name='GroupwiseAccountID',
            field=models.ForeignKey(blank=True, db_column='GroupwiseAccountID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.accountmaster'),
        ),
        AddFieldIfNotExists(
            model_name='salpurgroup',
            name='IGST1_CGST0',
            field=models.BooleanField(blank=True, db_column='IGST1_CGST0', null=True, verbose_name='IGST1 CGST0'),
        ),
        AddFieldIfNotExists(
            model_name='salpurgroup',
            name='Interstate_Y_WithinState_N',
            field=models.BooleanField(blank=True, db_column='Interstate_Y_WithinState_N', null=True, verbose_name='Interstate (Yes) / Within State (No)'),
        ),
        AddFieldIfNotExists(
            model_name='salpurgroup',
            name='IsGSTApplicableY1N0',
            field=models.BooleanField(blank=True, db_column='IsGSTApplicableY1N0', null=True, verbose_name='Is GST Applicable Y1N0'),
        ),
        AddFieldIfNotExists(
            model_name='salpurgroup',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, verbose_name='Is Active'),
        ),
        AddFieldIfNotExists(
            model_name='salpurgrouptran',
            name='ChargeAccountID',
            field=models.ForeignKey(blank=True, db_column='ChargeAccountID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.accountmaster'),
        ),
        AddFieldIfNotExists(
            model_name='salpurgrouptran',
            name='SalPurGroupID',
            field=models.ForeignKey(blank=True, db_column='SalPurGroupID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dashboard.salpurgroup'),
        ),
    ]

