# Generated by Django 6.0.3 on 2026-06-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_allow_blank_delivery_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('user_id', models.CharField(db_column='user_id', max_length=50, primary_key=True, serialize=False, verbose_name='User ID')),
                ('user_name', models.CharField(db_column='user_name', max_length=150, verbose_name='User Name')),
                ('role', models.CharField(choices=[('User', 'User'), ('Maker', 'Maker'), ('Checker', 'Checker'), ('Admin', 'Admin')], db_column='role', default='User', max_length=20, verbose_name='Role')),
                ('empid', models.CharField(db_column='empid', max_length=50, unique=True, verbose_name='Emp ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, verbose_name='Is Active')),
                ('user_created', models.CharField(blank=True, db_column='user_created', max_length=50, null=True, verbose_name='UserCreated')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_created', verbose_name='DateCreated')),
                ('user_modified', models.CharField(blank=True, db_column='user_modified', max_length=50, null=True, verbose_name='UserModified')),
                ('date_modified', models.DateTimeField(auto_now=True, db_column='date_modified', verbose_name='DateModified')),
            ],
            options={
                'verbose_name': 'User Master',
                'verbose_name_plural': 'User Masters',
                'db_table': 'tblUserMaster',
                'ordering': ['user_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='pursales',
            options={'managed': False, 'verbose_name': 'Purchase/Sales Header', 'verbose_name_plural': 'Purchase/Sales Headers'},
        ),
        migrations.AlterModelOptions(
            name='pursalestran',
            options={'managed': False, 'verbose_name': 'Purchase/Sales Detail', 'verbose_name_plural': 'Purchase/Sales Details'},
        ),
        migrations.AlterModelOptions(
            name='salpurgroup',
            options={'managed': False, 'verbose_name': 'Sales/Purchase Group', 'verbose_name_plural': 'Sales/Purchase Groups'},
        ),
        migrations.AlterModelOptions(
            name='salpurgrouptran',
            options={'managed': False, 'verbose_name': 'Sales/Purchase Group Transaction', 'verbose_name_plural': 'Sales/Purchase Group Transactions'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'managed': False, 'ordering': ['ZoneName']},
        ),
    ]
