# Generated by Django 6.0.3 on 2026-06-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_sal_pur_group_sp_and_view'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salpurgroup',
            table='vw_sal_pur_group',
        ),
    ]
