# Generated by Django 6.0.3 on 2026-10-05 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_approvalstages_gatepass_gatepasstran_grn_grntranmat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='Group Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Group',
                'verbose_name_plural': 'Item Groups',
                'db_table': 'tbl_item_group',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONTINUE', 'CONTINUE'), ('DISCONTINUE', 'DISCONTINUE')], default='CONTINUE', max_length=20, verbose_name='Status')),
                ('product_type', models.CharField(default='NORMAL', max_length=50, verbose_name='Type')),
                ('hide', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=10, verbose_name='Hide')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('item_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Code (F4)')),
                ('rack_no', models.CharField(blank=True, default='a1', max_length=50, null=True, verbose_name='Rack No.')),
                ('unit', models.CharField(default='PCS', max_length=20, verbose_name='Unit')),
                ('decimal_allowed', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10, verbose_name='Decimal')),
                ('fast_search', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10, verbose_name='Fast Search')),
                ('color_type', models.CharField(default='NORMAL', max_length=50, verbose_name='Color Type')),
                ('store', models.CharField(default='Default', max_length=50, verbose_name='Store')),
                ('store_code', models.IntegerField(default=0, verbose_name='Store Code')),
                ('item_type_code', models.CharField(default='1 NORMAL', max_length=50, verbose_name='Item Type')),
                ('group_allowed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10, verbose_name='Group')),
                ('group_name', models.CharField(blank=True, default='General', max_length=100, null=True, verbose_name='Group Name Text')),
                ('hsn_sac_allowed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10, verbose_name='HSN/SAC Allowed')),
                ('hsn_sac_code', models.CharField(blank=True, default='-BLANK-', max_length=50, null=True, verbose_name='HSN/SAC Code')),
                ('local_tax', models.CharField(choices=[('Taxable', 'Taxable'), ('Exempt', 'Exempt'), ('Nil Rated', 'Nil Rated')], default='Taxable', max_length=20, verbose_name='Local Tax')),
                ('central_tax', models.CharField(choices=[('Taxable', 'Taxable'), ('Exempt', 'Exempt'), ('Nil Rated', 'Nil Rated')], default='Taxable', max_length=20, verbose_name='Central Tax')),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='M.R.P.')),
                ('rate_a', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Rate-A')),
                ('conv_box', models.DecimalField(decimal_places=3, default=0.0, max_digits=18, verbose_name='CONV.BOX')),
                ('min_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Minimum Qty')),
                ('max_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Maximum Discount %')),
                ('min_margin', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Minimum Margin %')),
                ('sgst_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='SGST %')),
                ('igst_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IGST %')),
                ('p_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='P.RATE (Purchase Rate)')),
                ('rate_b', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Rate-B')),
                ('conv_case', models.DecimalField(decimal_places=3, default=0.0, max_digits=18, verbose_name='CONV.CAS')),
                ('max_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Maximum Qty')),
                ('purc_disc', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='PURC Disc %')),
                ('disc_less', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='DISC LESS')),
                ('cgst_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='CGST %')),
                ('cost_per_pcs', models.DecimalField(decimal_places=5, default=0.0, max_digits=18, verbose_name='COST/PCS')),
                ('rate_c', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Rate-C')),
                ('negative_billing', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10, verbose_name='NEGATIVE')),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Reorder Qty')),
                ('reorder_days', models.IntegerField(default=0, verbose_name='Days')),
                ('rate_mod_allowed', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10, verbose_name='F6/RATE±')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mfr (F3)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='dashboard.itemgroup', verbose_name='Product Group')),
            ],
            options={
                'verbose_name': 'Item Product',
                'verbose_name_plural': 'Item Products',
                'db_table': 'tbl_item_product',
                'ordering': ['item_name'],
            },
        ),
    ]
