-- Table: public.tblMaterial

-- DROP TABLE IF EXISTS public."tblMaterial";

CREATE TABLE IF NOT EXISTS public."tblMaterial"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    material_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    material_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    "UOM" smallint DEFAULT 0,
    "SKU" smallint DEFAULT 0,
    "SKU2" smallint DEFAULT 0,
    "MAT_CAT" smallint DEFAULT 0,
    "OB_QTY" numeric DEFAULT 0,
    "OB_QTY2" numeric DEFAULT 0,
    "USER_CREATED" character varying COLLATE pg_catalog."default",
    "DATE_CREATED" datemultirange,
    "USER_MODIFIED" character varying COLLATE pg_catalog."default",
    "DATE_MODIFIED" datemultirange,
    "ReOrderLevelSKU1" numeric,
    "CL_BAL" numeric(12,0)[],
    "CL_BAL2" numeric(12,3)[],
    "ReOrderLevelSKU2" numeric(12,3),
    "PurchaseGST" numeric(5,2),
    "SalesGST" numeric(6,2),
    "IsActive" boolean,
    "ActiveFromDate" date,
    "ACtiveTodate" date,
    "PackingID" smallint,
    CONSTRAINT "tblMaterial_pkey" PRIMARY KEY (id),
    CONSTRAINT "tblMaterial_material_code_key" UNIQUE (material_code)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."tblMaterial"
    OWNER to alpha_user;

COMMENT ON COLUMN public."tblMaterial"."PurchaseGST"
    IS 'Percentage of Purchase GST';

COMMENT ON COLUMN public."tblMaterial"."SalesGST"
    IS 'GST on Sales';

COMMENT ON COLUMN public."tblMaterial"."IsActive"
    IS 'this is a flag to identify whether this item is active or inactive';

COMMENT ON COLUMN public."tblMaterial"."ActiveFromDate"
    IS 'Date from when this item is active';

COMMENT ON COLUMN public."tblMaterial"."ACtiveTodate"
    IS 'Date to which this item is active or inactive';

COMMENT ON COLUMN public."tblMaterial"."PackingID"
    IS 'Bass, 10 kg, 5kg, 60 Kgs ';
-- Index: tblMaterial_material_code_343397ee_like

-- DROP INDEX IF EXISTS public."tblMaterial_material_code_343397ee_like";

CREATE INDEX IF NOT EXISTS "tblMaterial_material_code_343397ee_like"
    ON public."tblMaterial" USING btree
    (material_code COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    TABLESPACE pg_default;